import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import {readFileSync} from 'node:fs';
test('retired tools are unavailable and avatar requires a paid account',async({page,request})=>{for(const path of ['/ai-tools.html','/ai-tools.js','/ai-worker.js'])expect((await request.get(path)).status()).toBe(410);expect((await request.get('/api/avatar/access')).status()).toBe(401);await page.goto('/free-tools.html');await expect(page.locator('a[href*="ai-tools"]')).toHaveCount(0);await page.goto('/avatar.html');await expect(page.locator('#createAvatar')).toBeDisabled();await expect(page.locator('#access')).toContainText('Sign in');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
test('native photo auto-save and repeat download use full bytes; share opens native chooser',async({page})=>{
 await page.addInitScript(()=>{window.calls=[];window.AndroidBridge={startToolFile:(name,type)=>{window.calls.push(['start',name,type]);return true;},appendToolChunk:s=>{window.calls.push(['bytes',atob(s).length]);return true;},finishToolFile:share=>{window.calls.push(['finish',share]);return true;},cancelToolFile:()=>{}};});await page.goto('/free-tools.html');
 const bytes=await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=c.height=30;return Array.from(new Uint8Array(await(await new Promise(r=>c.toBlob(r))).arrayBuffer()));});await page.locator('#files').setInputFiles({name:'test.png',mimeType:'image/png',buffer:Buffer.from(bytes)});await page.locator('#run').click();await expect(page.locator('#status')).toHaveText('Done');await page.locator('#outputs button').first().click();await page.locator('#outputs button').nth(1).click();const calls=await page.evaluate(()=>window.calls);expect(calls.filter(c=>c[0]==='finish').map(c=>c[1])).toEqual([false,false,true]);expect(calls.filter(c=>c[0]==='bytes').every(c=>c[1]>0)).toBe(true);
});
test('avatar composes real video and own audio locally, auto-downloads and downloads again',async({page},info)=>{
 test.skip(info.project.name!=='chromium');test.setTimeout(180000);let posts=0;page.on('request',r=>{if(r.method()==='POST')posts++;});await page.route('**/api/avatar/access',r=>r.fulfill({json:{allowed:true,plan:'basic'}}));await page.goto('/avatar.html');
 const video=info.outputPath('source.mp4'),audio=info.outputPath('voice.wav');execFileSync('ffmpeg',['-y','-f','lavfi','-i','color=c=blue:s=160x120:d=1','-c:v','libx264',video],{stdio:'ignore'});execFileSync('ffmpeg',['-y','-f','lavfi','-i','sine=frequency=300:duration=1',audio],{stdio:'ignore'});
 const png=await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=c.height=120;const x=c.getContext('2d');x.fillStyle='orange';x.fillRect(0,0,120,120);return Array.from(new Uint8Array(await(await new Promise(r=>c.toBlob(r))).arrayBuffer()));});await page.locator('#portrait').setInputFiles({name:'me.png',mimeType:'image/png',buffer:Buffer.from(png)});await page.locator('#sourceVideo').setInputFiles(video);await page.locator('#narrationAudio').setInputFiles(audio);await page.locator('#narration').fill('Hello from my avatar');await page.locator('#portraitPreview').click({position:{x:150,y:200}});await page.locator('#createAvatar').click();await expect(page.locator('#avatarStatus')).toContainText('Confirm permission');await page.locator('#consent').check();const automatic=page.waitForEvent('download',{timeout:150000});await page.locator('#createAvatar').click();await expect(page.locator('#avatarResult video')).toBeVisible({timeout:150000});const first=await automatic;expect(first.suggestedFilename()).toMatch(/Avatar.*mp4/);await expect.poll(()=>page.locator('#avatarResult video').evaluate(v=>({w:v.videoWidth,h:v.videoHeight}))).toEqual({w:720,h:1280});const again=page.waitForEvent('download');await page.locator('#avatarResult button').first().click();expect((await again).suggestedFilename()).toBe(first.suggestedFilename());expect(posts).toBe(0);
});
test('local English TTS produces actual WAV audio for both voices',async({page},info)=>{
 test.skip(info.project.name!=='chromium');test.setTimeout(600000);await page.goto('/avatar.html');
 for(const voice of ['af_heart','am_michael']){const result=await page.evaluate(voice=>new Promise((resolve,reject)=>{const w=new Worker('/avatar-tts.js',{type:'module'});w.onerror=e=>{w.terminate();reject(Error(e.message));};w.onmessage=({data})=>{if(data.type==='error'){w.terminate();reject(Error(data.message));}if(data.type==='audio'){const bytes=new Uint8Array(data.wav);w.terminate();resolve({size:bytes.length,header:String.fromCharCode(...bytes.slice(0,4))});}};w.postMessage({voice,text:'Hello. Welcome to my video.'});}),voice);expect(result.header).toBe('RIFF');expect(result.size).toBeGreaterThan(24000);}
});
