import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import {readFileSync,writeFileSync,copyFileSync} from 'node:fs';
import {createHash} from 'node:crypto';

test('Smart Studio first paint is compact, captions edit, style survives reload',async({page},info)=>{
 await page.goto('/smart-studio.html');await expect(page.locator('h1')).toContainText('Your subject');await expect(page.locator('#export')).toBeDisabled();
 await page.locator('#brand').fill('Studio One');await page.locator('#saveStyle').click();await page.reload();await expect(page.locator('#brand')).toHaveValue('Studio One');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:info.outputPath('smart-studio.png'),fullPage:true});
});
test('real local MP4 export burns editable captions and keeps AAC audio; download, share and delete work',async({page},info)=>{
 test.skip(info.project.name!=='chromium','Heavy WASM export exercised once');test.setTimeout(180000);
 const input=info.outputPath('source.mp4');execFileSync('ffmpeg',['-y','-f','lavfi','-i','testsrc2=size=320x180:rate=15:duration=2','-f','lavfi','-i','sine=frequency=440:duration=2','-c:v','libx264','-c:a','aac','-shortest',input],{stdio:'ignore'});
 const posts=[];page.on('request',r=>{if(r.method()==='POST')posts.push(r.url());});
 await page.goto('/smart-studio.html');await page.locator('#source').setInputFiles(input);await page.locator('#follow').uncheck();await expect(page.locator('#export')).toBeEnabled();
 await page.locator('#addCaption').click();await page.getByLabel('Caption 1',{exact:true}).fill('Hello creator');await page.locator('#brand').fill('Smart Studio');await page.locator('#export').click();await expect(page.locator('#result')).toBeVisible({timeout:120000});
 const duration=await page.locator('#output').evaluate(v=>v.duration);expect(Math.abs(duration-2)).toBeLessThan(.12);
 const firstDownload=page.waitForEvent('download');await page.locator('#download').click();const out=info.outputPath('smart.mp4');await(await firstDownload).saveAs(out);const bytes=readFileSync(out);
 const streams=JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-of','json',out]));expect(streams.streams.find(s=>s.codec_type==='video').width).toBe(320);expect(streams.streams.some(s=>s.codec_type==='audio')).toBeTruthy();
 const audio=file=>execFileSync('ffmpeg',['-v','error','-i',file,'-map','0:a','-c:a','copy','-f','adts','-']);expect(createHash('sha256').update(audio(out)).digest('hex')).toBe(createHash('sha256').update(audio(input)).digest('hex'));
 const a=execFileSync('ffmpeg',['-v','error','-ss','0.5','-i',out,'-frames:v','1','-f','rawvideo','-pix_fmt','rgb24','-']);const b=execFileSync('ffmpeg',['-v','error','-ss','0.5','-i',input,'-frames:v','1','-f','rawvideo','-pix_fmt','rgb24','-']);expect(a.equals(b)).toBeFalsy();
 const download=page.waitForEvent('download');await page.locator('#download').click();expect((await download).suggestedFilename()).toBe('VideoUniquifier-Smart.mp4');
 await page.evaluate(()=>{navigator.canShare=()=>true;navigator.share=async({files})=>{window.sharedSize=files[0].size;};});await page.locator('#share').click();expect(await page.evaluate(()=>window.sharedSize)).toBe(bytes.length);
 await page.locator('#delete').click();await expect(page.locator('#result')).toBeHidden();expect(posts).toEqual([]);
});
test('real face detector follows a moving portrait and refuses featureless footage',async({page},info)=>{
 test.skip(info.project.name!=='chromium','Local model tested once');test.setTimeout(180000);
 const face=info.outputPath('portrait.jpg');writeFileSync(face,Buffer.from(readFileSync(new URL('./fixtures/face-test.b64',import.meta.url),'utf8'),'base64'));
 const input=info.outputPath('moving-face.mp4');execFileSync('ffmpeg',['-y','-f','lavfi','-i','color=c=gray:s=640x360:r=15:d=2','-loop','1','-i',face,'-filter_complex',"[1:v]crop=600:500:100:0,scale=300:330[p];[0:v][p]overlay=x='20+t*150':y=15",'-t','2','-c:v','libx264','-pix_fmt','yuv420p',input],{stdio:'ignore'});
 const posts=[];page.on('request',r=>{if(r.method()==='POST')posts.push(r.url());});await page.goto('/smart-studio.html');await page.locator('#source').setInputFiles(input);await expect(page.locator('#analyze')).toBeEnabled();await page.locator('#analyze').click();await expect(page.locator('#status')).toContainText('Face detected in',{timeout:90000});await page.locator('#playPreview').click();await expect(page.locator('#cropPreview')).toBeVisible();
 await page.locator('#export').click();await expect(page.locator('#result')).toBeVisible({timeout:120000});const saved=page.waitForEvent('download');await page.locator('#download').click();const out=info.outputPath('tracked.mp4');await(await saved).saveAs(out);const p=JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-of','json',out]));expect(p.streams[0].width).toBe(202);expect(p.streams[0].height).toBe(360);const faces=await page.evaluate(async()=>{const v=document.getElementById('output');await new Promise(r=>{v.onseeked=r;v.currentTime=1.5;});const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);const bitmap=await createImageBitmap(c);const worker=new Worker('smart-face-worker.js');return await new Promise((resolve,reject)=>{worker.onmessage=({data})=>{worker.terminate();data.error?reject(Error(data.error)):resolve(data.faces);};worker.postMessage({id:1,bitmap},[bitmap]);});});expect(faces.length).toBeGreaterThan(0);expect(faces[0].x).toBeGreaterThan(.25);expect(faces[0].x).toBeLessThan(.75);expect(posts).toEqual([]);
 const blank=info.outputPath('blank.mp4');execFileSync('ffmpeg',['-y','-f','lavfi','-i','color=gray:size=320x180:duration=1','-c:v','libx264',blank],{stdio:'ignore'});await page.locator('#source').setInputFiles(blank);await expect(page.locator('#analyze')).toBeEnabled();await page.locator('#analyze').click();await expect(page.locator('#status')).toContainText('Tracking is unavailable',{timeout:90000});await expect(page.locator('#export')).toBeDisabled();
});
test('real local word transcription produces editable captions without uploading media',async({page},info)=>{
 test.skip(info.project.name!=='chromium','Model download exercised once');test.setTimeout(360000);
 const wav=info.outputPath('speech.wav'),mp4=info.outputPath('speech.mp4');if(process.env.SMART_SPEECH_FIXTURE)copyFileSync(process.env.SMART_SPEECH_FIXTURE,wav);else execFileSync('espeak-ng',['-w',wav,'Hello, welcome to the video studio. This is a test of speech recognition.']);execFileSync('ffmpeg',['-y','-f','lavfi','-i','color=blue:size=320x180:rate=15','-i',wav,'-c:v','libx264','-c:a','aac','-shortest',mp4],{stdio:'ignore'});
 const posts=[];page.on('request',r=>{if(r.method()==='POST')posts.push(r.url());});await page.goto('/smart-studio.html');await page.locator('#source').setInputFiles(mp4);await page.locator('#follow').uncheck();await page.locator('#language').selectOption('en');await page.locator('#transcribe').click();await expect(page.locator('#status')).toContainText('Captions ready',{timeout:300000});const text=await page.locator('#captions .word').evaluateAll(inputs=>inputs.map(i=>i.value).join(' '));expect(text.toLowerCase()).toMatch(/welcome|studio|recognition/);expect(await page.locator('#captions .word').count()).toBeGreaterThan(3);await page.locator('#captions .word').first().fill('Welcome');await expect(page.locator('#captions .word').first()).toHaveValue('Welcome');await page.locator('#export').click();await expect(page.locator('#result')).toBeVisible({timeout:120000});expect(posts).toEqual([]);
});
test('cancel during actual local model loading releases the session and can retry',async({page},info)=>{
 test.skip(info.project.name!=='chromium','Local workers exercised once');const input=info.outputPath('cancel.mp4');execFileSync('ffmpeg',['-y','-f','lavfi','-i','color=gray:size=320x180:duration=1','-c:v','libx264',input],{stdio:'ignore'});await page.goto('/smart-studio.html');await page.locator('#source').setInputFiles(input);await expect(page.locator('#analyze')).toBeEnabled();await page.route('**/smart-models/**',route=>new Promise(resolve=>setTimeout(()=>route.continue().catch(()=>{}).finally(resolve),1500)));await page.locator('#analyze').click();await page.locator('#cancel').click();await expect(page.locator('#source')).toBeEnabled();await expect(page.locator('#status')).toContainText('Canceled');await page.locator('#follow').uncheck();await expect(page.locator('#export')).toBeEnabled();
});
