import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import {readFileSync} from 'node:fs';

test('dashboard metrics are compact and pricing fits without changing prices',async({page},info)=>{
 await page.goto('/',{waitUntil:'domcontentloaded'});await expect(page.locator('.statsGrid .stat b').first()).toBeVisible();expect(await page.locator('.statsGrid .stat b').first().evaluate(e=>parseFloat(getComputedStyle(e).fontSize))).toBeLessThanOrEqual(16);
 await page.screenshot({path:info.outputPath('dashboard.png'),fullPage:true});await page.locator('.navBtn[data-view="plans"]').evaluate(e=>e.click());await expect(page.locator('#plansView')).toHaveClass(/active/);await page.screenshot({path:info.outputPath('pricing.png'),fullPage:true});for(const price of ['$9','$24','$99'])await expect(page.locator('#plansView').getByText(price,{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('native camera opens with the current prompt settings',async({page})=>{await page.addInitScript(()=>{window.AndroidBridge={openTeleprompter:(...args)=>window.cameraArgs=args};});await page.goto('/free-tools.html');await page.locator('#script').fill('Read this script');await page.locator('#cameraOpen').click();expect(await page.evaluate(()=>window.cameraArgs)).toEqual(['Read this script',30,36,false]);});
test('browser camera records a playable local video and scrolls only during recording',async({browser},info)=>{
 test.skip(info.project.name!=='chromium');const context=await browser.newContext({permissions:['camera','microphone']});const page=await context.newPage();await page.goto('http://127.0.0.1:3000/free-tools.html');await page.locator('#script').fill('Hello from our studio.\n'.repeat(100));await page.locator('#cameraOpen').click();await expect(page.locator('#play')).toBeEnabled();await page.locator('#play').click();await expect(page.locator('#play')).toHaveAttribute('aria-pressed','true');await expect.poll(()=>page.locator('#prompter').evaluate(e=>e.scrollTop)).toBeGreaterThan(15);await page.locator('#play').click();await expect(page.locator('#cameraResults video')).toBeVisible();await expect(page.locator('#play')).toHaveAttribute('aria-pressed','false');const d=page.waitForEvent('download');await page.locator('#cameraResults button').first().click();expect((await d).suggestedFilename()).toMatch(/VideoUniquifier-Prompter-.*\.(mp4|webm)/);await page.locator('#cameraClose').click();expect(await page.locator('#cameraPreview').evaluate(v=>v.srcObject)).toBe(null);await context.close();
});
